### ISSUE TITLE
Kanban Setup

### ISSUE THREAD

**Issue by ZikaZaki** [ZikaZaki/JS-Capstone-Project#21]
# Kanban Board Setup
### Here's the link to our [kanban board](https://github.com/ZikaZaki/JS-Capstone-Project/projects/1).
-----
### **:exclamation:Important:** There are only two collaborators on this project:
- **👤 [Zakariya Al-Khamisi](https://github.com/ZikaZaki/).**
- **👤  [Bantealem Geto](https://github.com/Bantealem/).**

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
- good job setting up the project.

## Required Changes ♻️
- [ ] the cards with "student C" should be removed in a group of two
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ZikaZaki** [comment]
Hi @mikethreels , I already removed them. Thanks for your feedback.

**Comment by smunozmo** [comment]
Hi @ZikaZaki , 👋 

## Highlights 👏 

- Great work setting up your Kanban board! 🎉 

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

# APPROVED! 💯  💯  💯 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>


Cheers and Happy coding! 🤓 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
